### ISSUE TITLE
Trouble using opencv 3.0

### ISSUE THREAD

**Issue by faellacurcio** [cosmonautd/tiny-vpn#1]
The software no longer works using openCV 3.0. Raising the following error:
# ==================================================================

Traceback (most recent call last):
  File "turret.py", line 362, in set_frame
    frame, decision = detect.old_detection(frame, cascade_upperbody, cascade_face);
  File "/home/rafael/Desktop/turret-master/software/detect.py", line 7, in old_detection
    (rects_upperbody, frame) = imgutils.detect_pattern(frame, cascade_upperbody, (60,60))
  File "/home/rafael/Desktop/turret-master/software/imgutils.py", line 31, in detect_pattern
    rects = cascade.detectMultiScale(img, 1.2, 3, cv2.cv.CV_HAAR_DO_CANNY_PRUNING, min_rectangle)
AttributeError: 'module' object has no attribute 'cv'
# ==================================================================

The error could be fixed by hard coding the  value for this constant in the file imgutils.py line 31

Old line: 
    rects = cascade.detectMultiScale(img, 1.2, 3, cv2.cv.CV_HAAR_DO_CANNY_PRUNING, min_rectangle)

New line:
    rects = cascade.detectMultiScale(img, 1.2, 3, 1, min_rectangle)

I found someone with a similar problem at https://github.com/Itseez/opencv/issues/4387
The reply for this problem is:
"This is indeed still the case for the old cascades, but not for the cascades generated by the newer train_cascade interface. Since we were told that the haartraining interface will no longer be developed and actually be removed in the OpenCV3 interface, we should close down this bug, because fixing deprecated software is just not manageable."
